### ISSUE TITLE
Unable to resolve Tizen.Xamarin.Forms.Extension

### ISSUE THREAD

**Issue by gralin** [Samsung/Tizen-CSharp-Samples#10]
Hi, I asked this question already on the Tizen app developers forum but since it's also related to this repository, I will repeat it here. Having the development tools set up (latest Tizen SDK, emulator, etc.) I can't build the project because of missing Tizen.Xamarin.Forms.Extension package. It was unlisted from nuget:

https://www.nuget.org/packages/Tizen.Xamarin.Forms.Extension/

and the latest version there was **2.3.5-v00009** while the projects here reference it at version **2.4.0-v00014**. How can one build the sample then?

**Comment by darkleem** [comment]
The extension set of Tizen is used to be provided as Tizen.Xamarin.Forms.Extension package, but it is no longer supported. It is not available to provide all the features that developer wants, so we planed to provide extensions as the Samples.

I expect those samples would be the good examples that developers can refer or maybe simply copy or modify to use on their apps. The samples will be released as soon as prepared.
