### ISSUE TITLE
Provide C# companion Android sample using xamarin

### ISSUE THREAD

**Issue by EmilAlipiev** [Samsung/Tizen-CSharp-Samples#107]
Currently it doesnt seem to create a companion app using xamarin. because Samsung accessory sdk has only Jar support. I tried using Android Java bind library but it throws exception. please provide us a minimal working solution. you can find my attempt to create using xamarin.forms with dependency injection as attached.
[WearCompanion.zip](https://github.com/Samsung/Tizen-CSharp-Samples/files/3465108/WearCompanion.zip)

**Comment by sgchoi5** [comment]
Sorry for late answer. now, we have plan to support SAP (C# version).
Do you have another necessary things?

**Comment by EmilAlipiev** [comment]
hi thanks for the answer. i have already created a andorid binding library and nuget package. as you can see here https://github.com/EmilAlipiev/SamsungAccessorySDK.Net
This works perfectly fine. I was able to finish my app using this library but I have a problem in release mode using proguard. you can see the issue here. https://github.com/xamarin/xamarin-android/issues/4475

it seem like binding library doesnt work with proguard as it supposed to be. maybe you can find a solution or otherwise i have to wait until you complete your c# version
