### ISSUE TITLE
Sample HeartRateMonitor - Event OnDataUpdated not fired when screen off

### ISSUE THREAD

**Issue by Abesoddy** [Samsung/Tizen-CSharp-Samples#129]
Hello,

Is it possible to get the heart rate sensor data when the screen is off ? I tested the HeartRateMonitor sample but when the screen goes to sleep, the returned value is 0 on the event OnDataUpdated().

Best regards,

**Comment by Abesoddy** [comment]
I found this on native development but I can't find a solution with Tizen FX : https://developer.tizen.org/ko/forums/native-application-development/sensors-sleep-mode?langswitch=ko

**Comment by bwikbs** [comment]
@Abesoddy I guess you can use SensorPausePolicy. (https://samsung.github.io/TizenFX/API6/api/Tizen.Sensor.SensorPausePolicy.html)
In your case, You can add this code `heartRateMonitor.PausePolicy = SensorPausePolicy.None;
` to achieve what you want.

**Comment by Abesoddy** [comment]
Hello,

Indeed, thank you very much for your answer, this is exactly what I need !
