### ISSUE TITLE
Retrieving IMEI & cell information from Tizen Wearable

### ISSUE THREAD

**Issue by wajidp** [Samsung/Tizen-CSharp-Samples#140]
Hi Team
Is there a way to retrieve IMEI & cell information like mcc,mnc,lac,cell etc via Tizen dotnet api's?

**Comment by sgchoi5** [comment]
Hello, wajidp

I think.. it can't be accessed by Public API with normal privilege.
I will let someone add some comments for this case.

**Comment by wajidp** [comment]
Thanks @sgchoi5 for the update, we have a client requirement for the same. Is it possible via Knox SDK?

**Comment by sgchoi5** [comment]
@wajidp Could you let us know target device? Is it wearable?

**Comment by wajidp** [comment]
@sgchoi5 yes wearable tizen 4.0

**Comment by sgchoi5** [comment]
@wajidp  Let us know your available privilege level (Platform / Partner / Normal)

**Comment by wajidp** [comment]
partner

**Comment by sinikang** [comment]
For getting proper IMEI via telephony API,
Application should have  "http://tizen.org/privilege/securesysteminfo" privilege. 

Please refer the updated telephony API doxygen as following link.

https://developer.tizen.org/development/api-references/native-application?redirect=https://developer.tizen.org/dev-guide/5.5.0/org.tizen.native.mobile.apireference/group__CAPI__TELEPHONY__INFORMATION__MODEM.html

https://developer.tizen.org/development/api-references/native-application?redirect=https://developer.tizen.org/dev-guide/5.5.0/org.tizen.native.mobile.apireference/group__CAPI__TELEPHONY__INFORMATION__MODEM.html#ga7e0c134af4fe12c9074f5feaccf9f5cc

**Comment by wajidp** [comment]
@sinikang thanks
