### ISSUE TITLE
Bug Using SQLite

### ISSUE THREAD

**Issue by hadihashem** [Samsung/Tizen-CSharp-Samples#141]
Hello

I have the following open topic with Microsoft where abviously it has to be double checked by Samsung
https://github.com/MicrosoftDocs/xamarin-docs/issues/2675

In this issue, I simply wanted to add Tizen related project in this Xamarin.Form Sample:
https://docs.microsoft.com/en-us/samples/xamarin/xamarin-forms-samples/todo/

Can you please have a look on the attached files?
[Todo.zip](https://github.com/Samsung/Tizen-CSharp-Samples/files/4402421/Todo.zip)

Many thanks
Regards

**Comment by myroot** [comment]
I update Todo.Tizen.csproj file like below and it work propertly on Tizen 5.5 emulator
```
<Project Sdk="Tizen.NET.Sdk/1.0.9">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>tizen40</TargetFramework>
    <CopyLocalRuntimeTargetAssets>true</CopyLocalRuntimeTargetAssets>
  </PropertyGroup>

  <PropertyGroup Condition=" '$(Configuration)|$(Platform)' == 'Debug|AnyCPU' ">
    <DebugType>portable</DebugType>
  </PropertyGroup>
  <PropertyGroup Condition=" '$(Configuration)|$(Platform)' == 'Release|AnyCPU' ">
    <DebugType>None</DebugType>
  </PropertyGroup>

  <ItemGroup>
    <Folder Include="lib\" />
    <Folder Include="res\" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="sqlite" Version="3.13.0" />
    <PackageReference Include="SQLitePCLRaw.bundle_green" Version="2.0.2" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Todo\Todo.csproj" />
  </ItemGroup>

  

</Project>
```

**Comment by sgchoi5** [comment]
Hello,

First of all, you need to change this in your tizen project setting file.
<Project Sdk="Tizen.NET.Sdk/1.0.**3**"> => <Project Sdk="Tizen.NET.Sdk/1.0.**9**">

And, below SQLite sample works correctly with Tizen 5.5 Wearable Emulator.
Could you check how it works?
https://github.com/Samsung/Tizen-CSharp-Samples/tree/master/Wearable/SQLite.NET.Sample

thanks

**Comment by hadihashem** [comment]
@sgchoi5 The Tizen SQLite Sample is indeed working and also on Tizen 4.0 => Thank you for your indication which helped me to figure out the solution
In fact, it seems to be a bit more complicated using the Xamarin.Forms attached Sample
The conditions to make it running on Xamarin.Forms sample are:
1) Use minimum Tizen 5.0 target framework (w/o Tizen.NET.Sdk/1.0.9)
2) Reference SQLite & SQLitePCLRaw.provider.sqlite3.netstandard11 on Tizen Plateform Project
3) Add the following 2 lines in the constructor of the main class in the Tizen Plateform Project
- raw.SetProvider(new SQLite3Provider_sqlite3());
- raw.FreezeProvider(true);
4) No need for special privileges and the PCL project remains as is and will be then working for all platforms the same incl. Tizen
I attached the updated project sample
[Todo.zip](https://github.com/Samsung/Tizen-CSharp-Samples/files/4437761/Todo.zip)
Regards
