### ISSUE TITLE
How to read cookies?

### ISSUE THREAD

**Issue by hadihashem** [Samsung/Tizen-CSharp-Samples#144]
Hello
Based on the following article, the function WebView.EvaluateJavaScriptAsync is not implemented on Tizen.Net plateform
https://docs.microsoft.com/en-us/dotnet/api/xamarin.forms.webview.evaluatejavascriptasync?view=xamarin-forms
Is there another way to read cookies?
Regards

**Comment by younghajung** [comment]
WebView.EvaluateJavaScriptAsync is not supported yet on Tizen port of Xamarin.Forms.
But, I think you can get cookies on runtime using [AddJavaScriptMessageHandler](https://samsung.github.io/TizenFX/latest/api/Tizen.WebView.WebView.html#Tizen_WebView_WebView_AddJavaScriptMessageHandler_System_String_Tizen_WebView_JavaScriptMessageHandler_).

Before loading URL, add the handler for the message from web contents.
`
            _webview.AddJavaScriptMessageHandler("CookieHandler", (message) =>
            {
                if (message.Name.Equals("CookieHandler"))
                {\
                    var cookie = message.GetBodyAsString();
                }
            });
`

After load complete, evaluate javascript to send message with cookie.
`
           _webview.LoadFinished += (s, e) =>
            {
                _webview.Eval("window.CookieHandler.postMessage(window.document.cookie);");
            };
`

**Comment by hadihashem** [comment]
Bingo !
I added this in OnElementChanged of the CustomerWebViewRenderer and it works perfectly
Thanks ..
