### ISSUE TITLE
Issue with XAML Previewer in any sample project

### ISSUE THREAD

**Issue by Filliny** [Samsung/Tizen-CSharp-Samples#146]
Xaml preview not rendering - "An Android Application project must reference the project containing this XAML file in order to render in the Previewer"
Is something is missing ?

**Comment by sgchoi5** [comment]
Hello, 
Xaml Preview is not supported.

**Comment by rookiejava** [comment]
Thank you for reaching out. Unfortunately, XAML Previewer is not available on tizen project. (As far as I now, iOS and Android are only supported.) If you have any question or issue related to XAML Previewer, please visit [here](https://docs.microsoft.com/en-us/xamarin/xamarin-forms/xaml/xaml-previewer/?pivots=windows).

**Comment by Filliny** [comment]
Ok -  thanx) I found some workaround of how to  have Previewer working - is to add Tizen.net xaml project to existing Xamarin multiplatform (android/iOS) solution. Anyway  u may need apply some changes to views to make it look apropirate for TV. https://developer.samsung.com/tizen/blog/en-us/2019/10/02/add-a-tizen-project-to-xamarinforms-applications
