### ISSUE TITLE
Sample to do calls from associated smartphone

### ISSUE THREAD

**Issue by sondavide** [Samsung/Tizen-CSharp-Samples#152]
There isn't a sample to do a call from associated smartphone. Is it still used the privilage "http://tizen.org/privilege/call"?

**Comment by sgchoi5** [comment]
Not able to make a call by code.
Instead, you can use Application Control - Call
Refer to this page: https://docs.tizen.org/application/native/guides/app-management/common-appcontrols

**Comment by sondavide** [comment]
should I use a native service? because the privilege  "http://tizen.org/privilege/call" does not exist in .net

**Comment by sgchoi5** [comment]
You can use C# version. refer to app control section of TizenFx (C#) API Reference.
If you can't find the call privilege from the dropbox, you can add it via text editor.

**Comment by sondavide** [comment]
Thank you, I add the privilege in the manifest as custom privilege and I request it at runtime.
