### ISSUE TITLE
No samples for AnimationView (rlottie) in the repo

### ISSUE THREAD

**Issue by poltesting0** [Samsung/Tizen-CSharp-Samples#160]
I can't find any app example for the [AnimationView](https://samsung.github.io/TizenFX/stable/api/ElmSharp.AnimationView.html) API in the repository. I'm interested in developing a **TV CSharp Xamarin.Forms** app which uses json (rlottie) animations. Could you add a sample app which renders a json animation? Thank you.

**Comment by rookiejava** [comment]
Here you go :-)
https://github.com/TizenAPI/ElottieSharp
