### ISSUE TITLE
Wearables - Adding Pin to MapView

### ISSUE THREAD

**Issue by nycmets** [Samsung/Tizen-CSharp-Samples#17]
Hello,
I am testing the sample .NET Code for Maps provided in this area (https://github.com/Samsung/Tizen-CSharp-Samples/tree/master/Wearable/Maps) and it seems that no pin image loads when a new pin is added to a mep.

var pin = new Pin(new Geocoordinates(DEFAULT_LAT, DEFAULT_LON));
s_mapview.Add(pin); 
 
This works for a Mobile application, but not Wearable. Is this a known limitation of the platform or does the pin need a special sizing for Wearables?

**Comment by sgchoi5** [comment]
Please wait a little longer. The person in charge is not available.

**Comment by jomui** [comment]
Can you check this on the Wearable of the lastest version ?
As I know, some version of the Wearable has a problem about the resource path for .Net.
But, this is not related in the Map framework.
Thanks.
