### ISSUE TITLE
Tag Read on actual device

### ISSUE THREAD

**Issue by donoo** [Samsung/Tizen-CSharp-Samples#202]
Hello,

Does NFCSampleApp for wearable app work on actual device and read nfc tag? 
I was trying read nfc tag in web app but it did not work. As per Samsung, nfc tag read support is not in galaxy watch. 

I will try it tonight but wanting to check 

Regards,

Amin

**Comment by jh8801jung** [comment]
Hi, donoo.

NFC Tag feature is not supported in Galaxy watch.
This is because NFC Chip hardware does not support tag features.

Thanks.
Jihoon.

**Comment by donoo** [comment]
Thanks @jh8801jung  for your reply! 

There is hardly any samsung wearable device which supports NFC read. I m not sure if this is hardware limitation or just Software limitation?

It can open new possibilities with Samsung wearable if this is supported.

Regards,
Amin
