### ISSUE TITLE
Question: how to prevent screen timeout

### ISSUE THREAD

**Issue by Jazzman123** [Samsung/Tizen-CSharp-Samples#204]
I’ve been playing with the Tizen .NET SDK for Wearables to write an app for my Samsung Galaxy Watch Actvie2.  I’m using these sample apps as a guide (they have been very helpful).
There is one thing that I’d like my app to do that I can’t figure out.  How do I prevent the screen from timing out and changing to the Off display state?  I’ve seen other apps do this, so I’m assuming it’s possible.  I don’t see any sample that’s doing this kind of thing, but I’m also not sure what to look for.  I tried creating a Display.StateChanged event handler that detects when the state changes to Off and then changing it back to Normal, but that isn’t working.  

Any help would be greatly appreciated.

**Comment by sgchoi5** [comment]
Hello, could you check this question and answer? I hope it could be answer.

https://developer.tizen.org/forums/tizen-.net/screen-always-on

**Comment by Jazzman123** [comment]
Yes!  That's exactly the information I was looking for.  Thanks so much!  I will ask further questions in that developer forum instead of here.
It is interesting that the methods listed in the [Power class here](https://docs.tizen.org/application/dotnet/api/tizenfx/api/Tizen.System.Power.html#methods) doesn't include the RequestLock and ReleaseLock methods.  The [Power class described here](https://developer.tizen.org/dev-guide/csapi/api/Tizen.System.Power.html#methods) is more up-to-date.
