### ISSUE TITLE
Storage 

### ISSUE THREAD

**Issue by hellhound858** [Samsung/Tizen-CSharp-Samples#220]
Hello,

Is there a way to store data in tizen .net? I.E data generated by your app stored on said wearable device. As I have been looking around and have not been able to find a way to do this.

Thank you for any help provided.

:)

**Comment by sgchoi5** [comment]
Hello, you can save your data in application folder of your device. could you check the AudioIOSample in Mobile folder?
To get proper path: refer to DirectoryInfo class of TizenFx (C# Device API of Tizen Platform)
https://samsung.github.io/TizenFX/API8/api/Tizen.Applications.DirectoryInfo.html

To create file: refer to File class of .netcore
https://docs.microsoft.com/en-us/dotnet/api/system.io.file?view=net-5.0

**Comment by hellhound858** [comment]
So this will work when creating wearable .net applications as well? I am creating a time table app (to learn) and I need to know how to save lessons and times to the device. I'll give the info you gave me a read. Thank you so much.

**Comment by sgchoi5** [comment]
Small portion of UI Code could be different. but, there is no difference for using TizenFx and .netcore API.

**Comment by hellhound858** [comment]
Ok thank you so much. :)

**Comment by hellhound858** [comment]
How do I sort this error?
_**With this:**_
`private Tizen.Applications.DirectoryInfo DI = new Tizen.Applications.DirectoryInfo();`

 _**Error:**_
Error	CS1729	'DirectoryInfo' does not contain a constructor that takes 0 arguments
