### ISSUE TITLE
How to debug Segmentation fault ? 

### ISSUE THREAD

**Issue by ahmad-crossplatform** [Samsung/Tizen-CSharp-Samples#31]
Hello there , I am making a renderer for the MultimediaView . However , when it executes `base.OnElementChanged(e); `  I get an error `Segmentation fault`  what do you guys do when this happens  ? how can you find out the problem ?

**Comment by sgchoi5** [comment]
Sorry for late answer, Could you update Visual Studio plugin and Tizen SDK?
