### ISSUE TITLE
Xamarin Forms ChromeCast

### ISSUE THREAD

**Issue by andersonvieiragomeslopes** [Samsung/Tizen-CSharp-Samples#34]
Hi.
Is there any customization of the video player so that it can work with ChromeCast?

**Comment by sgchoi5** [comment]
Hello, Anderson

Sorry for late answer,
At now, there is no similar customization for ChromeCase.
We will try to add more C# Sample apps.

thanks

**Comment by andersonvieiragomeslopes** [comment]
@sgchoi5 My intention would be to play videos from my cell phone to smartTV, something very similar to what the youtube app does when we are connected to the same network where there is a Chromecast or SmartTV, even if you do not have a sample here, you could indicate me tutorials or some material about ?
