### ISSUE TITLE
Segmentation Fault while using Google Drive .NET API

### ISSUE THREAD

**Issue by FlaviusBejan** [Samsung/Tizen-CSharp-Samples#64]
Hello,

I'm trying to make a Google Drive App.
I've made all the steps from the home page, have the latest version for the VS Plugin and Tizen SDK (as asked here: [https://github.com/Samsung/Tizen-CSharp-Samples/issues/31](url))
I've used Google's .NET Quickstart guide ([https://developers.google.com/drive/api/v3/quickstart/dotnet](url)) in a console application, in which it works perfectly, but in the Tizen 5.0 Class Library (added to the Blank App Xamarin Form) I stumble only on "Segmentation Fault".

The first one is when it's trying to read the credentials.json file (which was added to the solution and set to be copied to the location of the executable).
I've fixed this by using StorageManager.Storages and looking for the Internal StorageType, then created the file, if it didn't exist, and adding the json to it (using System.IO.File). I've also replaced "new FileStream("credentials.json", ...)" with "System.IO.File.Open(credentialsPath, ...)".
The only hint I had for this was the call stack which indicated that there was a problem when accessing the memory (see first image).

The second one is when it tries to call AuthorizationAsync. Unfortunately this it the first place in which I couldn't figure out what I should do because the call stack wasn't of help (see second image).

The third one is when I've tried a new approach. This one goes further, but fails when it tries to get the files from the service. The call stack shows that there is a memory access problem, but I can't figure out what might cause this (see third image).
Screenshots: [https://imgur.com/a/J6mkfYe](url)

I have the following privileges in the manifest: internet, network.get, mediastorage, systemsettings, externalstorage, filesystem.read, filesystem.write. The last five were added thinking that they are the fix for the first problem and I've left them just in case.

Is there a way to get more information on the actual error or is there a correct way of doing a connection with Google Drive ?

Thank you,
Flavius

**Comment by myroot** [comment]
Please check relative path. 
default cwd(current working directory) is not root of app.

maybe it will be help
https://samsung.github.io/TizenFX/API4/api/Tizen.Applications.DirectoryInfo.html#Tizen_Applications_DirectoryInfo_Resource

**Comment by FlaviusBejan** [comment]
Hello Mr. Lee,

Thank you for your response.
By using "Application.Current.DirectoryInfo.Cache;" instead of "StorageManager.Storages" fixed the first problem that I've mention.
As for the second problem, making the "GetAllFiles" method an async Task and using a try catch when calling it, I was able to get a little bit more information on why it fails. The exception message from "GoogleWebAuthorizationBroker.AuthorizeAsync" is: "Failed to launch browser with \"https://accounts.google.com/o/oauth2/v2/auth?XYZ" for authorization. See inner exception for details.", with the inner exception details: "No such file or directory".
In the Console Application "GoogleWebAuthorizationBroker.AuthorizeAsync" opens the default browser with using the OAuth2 link, but in this case it seems that it doesn't find the browser.
I've checked the Emulator to see if there is the is a browser application and it is, "Internet".
Is there an extra step to set this as default, or there is no way for the current SDK to support the way Google opens a browser ?

Thank you and I wish you a good day,
Flavius

**Comment by myroot** [comment]
Google Library not support Tizen platform(tizen40, it compatible with netcore 2.0, netstandard2.0) yet.
https://github.com/googleapis/google-api-dotnet-client/blob/620b8f1792d876f0bf9bdd2379d493aa4bbb2015/Src/Support/Google.Apis.Auth/OAuth2/LocalServerCodeReceiver.cs#L427-L462

**Comment by myroot** [comment]
To open browser in your app, you should use AppControl with http://tizen.org/privilege/appmanager.launch privilege

``` c#
            Tizen.Applications.AppControl appControl = new Tizen.Applications.AppControl();
            appControl.Operation = Tizen.Applications.AppControlOperations.View;
            appControl.Uri = "https://google.com";
            try
            {
                Tizen.Applications.AppControl.SendLaunchRequest(appControl);
            }
            catch (Exception err)
            {
                System.Console.WriteLine(err.Message);
            }
```

**Comment by FlaviusBejan** [comment]
Thank you for your time and help.
I'll try to make this app in a different language or wait until the Google Library will be supported, which I hope it will be soon.

Have a nice day,
Flavius

**Comment by myroot** [comment]
Now you can use google api client for .net library in Tizen with xamarin.forms
Here is a solution
https://gist.github.com/myroot/d998b80dbf52ad7632dfe519ca992fdc
