### ISSUE TITLE
.NET TV apps doesn't show in apps list / smart hub

### ISSUE THREAD

**Issue by dotMorten** [Samsung/Tizen-CSharp-Samples#71]
I'm guessing there's something wrong with the manifests - none of the TV apps seem to appear in the apps list / smarthub, so there's no way to launch these apps on the TV without doing it remotely from Visual Studio.

**Comment by sgchoi5** [comment]
Sorry for late answer.
Plz, refer to this page.
https://developer.tizen.org/forums/tizen-.net/smart-hub-tizen-4.0-tv-.net-app?langredirect=1
