### ISSUE TITLE
Web App Sample versoin

### ISSUE THREAD

**Issue by CorporateDrone** [Samsung/Tizen-CSharp-Samples#92]
Thank you for making this sample. Do you have a Cordova Web app version? I am unable to get Tizen's instructions working for reading NFC.

**Comment by sgchoi5** [comment]
Contacting proper developer for your question...

**Comment by pkosko** [comment]
Hello,
regarding to Cordova Web Application, Tizen does not support Cordova directly using Cordova CLI. Even though CLI is not supported, Tizen web application supports a set of cordova plugins using a workaround based on procedure of manual inject JS code related to Cordova plugins.
The sample of application capable to use Cordova plugins is available here: in git project:
 [_review.tizen.org:29418/platform/core/api/cordova-plugins_](https://review.tizen.org/gerrit/gitweb?p=platform/core/api/cordova-plugins.git;a=tree;f=sample;h=ef3b98f163ca9a65f4a06f6ec7aff77d45dff3d6;hb=refs/heads/tizen) branch: _tizen_ directory: _sample_ 
The procedure of using it with Tizen Studio is described here: _https://cordova.apache.org/docs/en/5.0.0/guide/platforms/tizen/_
Here is the list of available features of Cordova _https://developer.tizen.org/development/guides/web-application/cordova_

According to NFC, you didn't provide much details, but here is the guide which describes most common scenarios of using NFC - _https://developer.tizen.org/development/guides/web-application/connectivity-and-wireless/nfc_
Full API reference is here: _https://developer.tizen.org/dev-guide/5.0.0/org.tizen.web.apireference/html/device_api/mobile/tizen/nfc.html_
