### ISSUE TITLE
Wearable App crashes on TW3 w/ prebuilt plugins

### ISSUE THREAD

**Issue by HJLeee** [Samsung/Tizen-CSharp-Samples#93]
@rzimnoch, @t-zalewski 

Please check details [here](https://github.sec.samsung.net/dotnet/home/issues/306)
We found `Weather` and `HeartRateMonitor` are crashed when prebuilt plugins are installed.

**Comment by sgchoi5** [comment]
Sent information to proper person.

**Comment by t-zalewski** [comment]
Hey,
I can't reproduce the issue. I used:
Target : TW3 (Wearable)
Binary : tizen-unified_20190522.1_wearable-wayland-armv7l-tw3
Plugin : tizen_5.5_tw3 (06c523c30ad3844ac2cae4c62d0768720423c30f)

I checked both actual ```Weather``` and ```HeartRateMonitor``` app and I didn't notice any problems.

**Comment by HJLeee** [comment]
After short investigation, this happens only when `kill` with `SIGTERM` the app and then next time app is asked to be launched.
I think the application or library it using registers `SIGTERM sigaction` and it may causes the crash.
